### ISSUE TITLE
node server start failed

### ISSUE THREAD

**Issue by gilfuser** [cannc4/Siren#13]
Hi.
I'm trying to try Siren. It look very interesting. I hope I can manage to have it working.
I'm having a problem. I'm on Linux Ubuntu 16.10. I'm falling the instructions in the Readme and when I do `npm run siren`
I tried with node 7.9 and 6.10
I get Errors. I'm attaching the log file and here is what I get in the console:
```
> Siren@0.1.1 siren /home/gilfuser/Siren
> node server/start.js

module.js:591
    throw err;
    ^

SyntaxError: /home/gilfuser/Siren/config/config.json: Unexpected token } in JSON at position 534
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gilfuser/Siren/server/app.js:2:1)
    at Module._compile (module.js:571:32)
    at loader (/home/gilfuser/Siren/node_modules/babel-register/lib/node.js:144:5)

npm ERR! Linux 4.8.0-46-lowlatency
npm ERR! argv "/home/gilfuser/.nvm/versions/node/v7.9.0/bin/node" "/home/gilfuser/.nvm/versions/node/v7.9.0/bin/npm" "run" "siren"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Siren@0.1.1 siren: `node server/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Siren@0.1.1 siren script 'node server/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Siren package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Siren
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Siren
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gilfuser/.npm/_logs/2017-04-12T19_34_08_413Z-debug.log

[2017-04-12T19_34_08_413Z-debug.log.zip](https://github.com/cannc4/Siren/files/917646/2017-04-12T19_34_08_413Z-debug.log.zip)
```

**Comment by gilfuser** [comment]
Got it! So simple. Thanks

**Comment by merttoka** [comment]
Glad that you did it! Please keep posting issues for future bugs.
