### ISSUE TITLE
Failing to load SuperCollider

### ISSUE THREAD

**Issue by NPolikurov** [cannc4/Siren#39]
Hi! I'm a Tidal user, so my regular Tidal + SuperCollider setup works fine.
I'm on Ubuntu.

my configs:
`{
 "userpath": "/Users/nikolai/",
 "ghcipath": "/usr/bin/ghci",
 "sclang": "/usr/bin/sclang",
 "scsynth": "/usr/bin/scsynth",
 "sclang_conf": "",
 "tidal_boot": "",
 "scd_start": ""
}`

Followed your guide, but i'm getting this error as soon as I try to evaluate something:
` ## -->   Server started at http://localhost:3001
Send SuperCollider:  (
a = play{t=Impulse.ar(6)+Dust.ar(0);x=(TExpRand.ar(_,_,t));Limiter.ar(GVerb.ar(GrainFM.ar(2,t,x.(1e-4,0.01),f=x.(80,400),f/4,9),9,0.5))};
)`

`TypeError: Cannot read property 'interpret' of undefined
    at REPL.sendSC (/home/nikolai/Music/Siren/server/app.js:388:13)
    at sendScPattern (/home/nikolai/Music/Siren/server/app.js:439:31)
    at /home/nikolai/Music/Siren/server/app.js:542:11
    at Layer.handle [as handle_request] (/home/nikolai/Music/Siren/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nikolai/Music/Siren/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nikolai/Music/Siren/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nikolai/Music/Siren/node_modules/express/lib/router/layer.js:95:5)
    at /home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:275:10)
    at /home/nikolai/Music/Siren/server/app.js:410:7
    at Layer.handle [as handle_request] (/home/nikolai/Music/Siren/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:317:13)
    at /home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:335:12)
    at next (/home/nikolai/Music/Siren/node_modules/express/lib/router/index.js:275:10)`

**Comment by merttoka** [comment]
Hey @NPolikurov, 

There seems like a problem with the config file. Could you try with the following configuration?

```
{ "userpath": "/Users/nikolai/", 
  "ghcipath": "/usr/bin/ghci", 
  "sclang": "/usr/bin/sclang", 
  "scsynth": "/usr/bin/scsynth",  
  "sclang_conf": "### path to your sclang_conf.yaml file (probably in Application Support) ###", 
  "tidal_boot": "/home/nikolai/Music/Siren/config/tidal-boot-default.hs", 
  "scd_start": "/home/nikolai/Music/Siren/config/scd-start-default.scd" }
```

**Comment by NPolikurov** [comment]
No luck.. here is my updated config, with all existing files:

`{
 "userpath": "/Users/nikolai/",
 "ghcipath": "/usr/bin/ghci",
 "sclang": "/usr/bin/sclang",
 "scsynth": "/usr/bin/scsynth",
 "sclang_conf": "/home/nikolai/.config/SuperCollider/sclang_conf.yaml",
 "tidal_boot": "/home/nikolai/Music/Siren/config/tidal-boot-default.hs",
 "scd_start": "/home/nikolai/Music/Siren/config/scd-start-default.scd"
}`

and the same old error:
` ## -->   Server started at http://localhost:3001
Send SuperCollider:  (
a = play{t=Impulse.ar(6)+Dust.ar(0);x=(TExpRand.ar(_,_,t));Limiter.ar(GVerb.ar(GrainFM.ar(2,t,x.(1e-4,0.01),f=x.(80,600),f/4,9),9,0.5))};
)`

`TypeError: Cannot read property 'interpret' of undefined
    at REPL.sendSC (/home/nikolai/Music/Siren/server/app.js:388:13)
    at sendScPattern (/home/nikolai/Music/Siren/server/app.js:439:31)
    at /home/nikolai/Music/Siren/server/app.js:542:11
    at Layer.handle [as handle_request] (/home/nikolai/Music/Siren/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nikolai/Music/Siren/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nikolai/Music/Siren/node_modules/express/lib/router/route.js:112:3)`

I have tried launching SuperCollider from my terminal with just `sclang` command, and using it with Tidal (Atom), and it works fine..

**Comment by cannc4** [comment]
It seems like you haven't booted the sc server yet. You can do that by pressing the `Start Server` button at the top-right corner of the interface

**Comment by NPolikurov** [comment]
Perfect! That was it. I suggest editing the guide to include this last (now obvious) step. Thanks!
